name: gt-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: grift
            suite: grift
          - tool: ins-and-outs
            suite: migeed
          - tool: no-context
            suite: migeed
          - tool: smt
            suite: migeed
      
    steps:
    - uses: actions/checkout@v2
    - id: cache-cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Compile (Rust)
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: cargo build
    - name: Unit tests
      run: cargo test -- --nocapture
    - name: ${{ matrix.tool }} on ${{ matrix.suite }}
      run: ./test-runner.sh ${{ matrix.tool }} ${{ matrix.suite }}
