name: gt-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: cache-cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Compile (Rust)
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: cargo build
    - name: Grift tests w/safe SMT
      run: ./test-runner.sh grift grift
