name: gt-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: cache-cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Compile (smt)
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: cargo build
    - name: Unit tests
      run: cargo test -- --nocapture
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: cache-cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Compile (smt)
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: |
        echo Build step ran but the results weren't in cache. What's up?
        exit 1
    - name: TypeWhich and InsAndOuts benchmarks
      run: |
        cargo run -- benchmark benchmarks.yaml --ignore Gtubi MGT MaxMigrate > test.results.yaml
        ./bin/yamldiff test.expected.yaml test.results.yaml
    - name: Grift frontend
      run: ./test-runner.sh grift grift

