name: gt-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile (Rust)
      run: cargo build
    - name: Grift tests
      run: ./test-runner.sh grift grift
